// I/O & params
params.outdir            = "/mount/britton/Jose/Jobs/Jason/2025-09-30-obtain-ANI-results-type-strain-nextflow-run/workflow-output"
params.fastani_max_refs  = 20
params.fastani_prefer_type = true
params.fastani_required  = false

profiles {
  MAB {
    process.executor = 'slurm'
    process.scratch  = true
    process.maxRetries = 3
    process.errorStrategy = 'terminate'

    process {
      withName: BUILD_FASTANI_PANEL { cpus = 4; time = '4h'; memory = '8 GB' }
      withName: FASTANI_BATCH       { cpus = 8; time = '2h'; memory = '8 GB' }
      withName: FASTANI_ANNOTATE_TYPES { cpus = 1; time = '30m'; memory = '1 GB' }
    }
  }
}

