// -------- I/O parameters --------
params.index = "/mount/britton/Jose/Jobs/Jason/2026-05-24-Phylogram-Tree-Genus-Closest-Neighbor-Lawsonibacter-hominis-Inclusion-Nextflow-Run/workflow/nextflow_readfile.csv"
params.outdir = "/mount/britton/Jose/Jobs/Jason/2026-05-24-Phylogram-Tree-Genus-Closest-Neighbor-Lawsonibacter-hominis-Inclusion-Nextflow-Run/workflow-output"
params.genome = "/mount/britton/Jose/Jobs/Jason/2026-05-24-Phylogram-Tree-Genus-Closest-Neighbor-Lawsonibacter-hominis-Inclusion-Nextflow-Run/workflow/stage_genome.py"
params.python = "/usr/bin/python" 

// Tool DBs used by this workflow
params.gtdbtk_db     = "/mount/britton/leap/dbs/gtdbtk"
params.plassembler_db = "/mount/britton/Jose/DBs/plassembler_db"

// for outgroup for phylogenetic tree 
params.outgroup_acc = "GCA_000010565" 

params.type_accession = null 
params.sample = null
params.skip_gtdb_refs = false  

profiles {
  standard {
    process.executor = 'local'
  }

  MAB {
    executor {
      name            = 'slurm'
      queueSize       = 5
      submitRateLimit = '5/1min'
      exitReadTimeout = '3600 sec'
      killBatchSize   = 5
      retry.delay     = '5 sec'
    }

    // Make tools see their DBs without exporting inside scripts
    env.GTDBTK_DATA_PATH = params.gtdbtk_db

    process {
      executor      = 'slurm'
      scratch       = true
      maxRetries    = 3
      errorStrategy = 'terminate'

      withName: PORECHOP_ABI              { cpus = 8;  time = '2h';  memory = '8 GB'  }
      withName: FLYE                      { cpus = 16; time = '48h'; memory = '64 GB' }
      withName: QUAST_QC                  { cpus = 4;  time = '8h';   memory = '64 GB' }
      withName: CHECKM1_QC                { cpus = 4;  time = '24h';  memory = '64 GB' }
      withName: DOWNLOAD_REFS             { cpus = 8;  time = '8h';  memory = '32 GB' } 
      withName: GTDB_DENOVO_ALIGN         { cpus = 8;  time = '72h';  memory = '64 GB' } 
      withName: IQTREE2                   { cpus = 8;  time = '240h';  memory = '64 GB' }
    }
  }
}

