// IO parameters
params.index = "/mount/britton/Jose/Jobs/Jason/2026-05-19-BAKTA-Annotation-Pseudo-Strain/workflow/nextflow_readfile.csv"
params.outdir = "/mount/britton/Jose/Jobs/Jason/2026-05-19-BAKTA-Annotation-Pseudo-Strain/workflow-output"           

profiles {

    standard {
        process.executor = 'local'
    }

    MAB {
        
        executor {
            
            name = 'slurm'
            queueSize = 100
            submitRateLimit = '50/1min'
            exitReadTimeout = '3600 sec'
            killBatchSize = 10
            retry.delay = '5 sec'
        }
 
        process {

            // environment management
            beforeScript = """
            module load anaconda3/2023.03-1
            """

            // job management
            executor = 'slurm'
            scratch = true

            // error management
            maxRetries = 3 
            errorStrategy = 'terminate'

            withName: bakta {
                cpus = 1
                time = '24.h'
                memory = '32.G'
            }

        }

    }

}
