// I/O & params
params.outdir = "/mount/britton/Jose/Jobs/Jason/2025-10-04-Obtaining-AAI-Results-and-Tree-Nextflow-run/workflow-output"
params.ezaai_env = "/mount/britton/Jose/conda-envs/mamba/envs/ezaai"
params.genome = "/mount/britton/Jose/Jobs/Jason/2025-10-04-Obtaining-AAI-Results-and-Tree-Nextflow-run/workflow/stage_genome.py"
params.python = "/usr/bin/python"

profiles {
  MAB {
    process.executor = 'slurm'
    process.scratch  = true
    process.maxRetries = 3
    process.errorStrategy = 'terminate'

    process {

      withName: AAI_EZAAI { cpus = 16; time = '4h'; memory = '32 GB' } 

    }
  }
}

