// I/O & params
params.outdir = "/mount/britton/Jose/Jobs/Jason/2025-09-30-obtain-ANI-results-type-strain-nextflow-run/workflow-output"
params.fastani_max_refs  = 20
params.fastani__type = true
params.fastani_required  = false
params.fastani_prefer_type   = true
params.fastani_require_type  = true
params.fastani_ncbi_from_type = true
params.gtdb_tokens = "/mount/britton/Jose/Jobs/Jason/2025-09-30-obtain-ANI-results-type-strain-nextflow-run/workflow/gtdb_tax_tokens.py"
params.python       = "/usr/bin/python"

profiles {
  MAB { 
    process.executor = 'slurm' 
  // Local execution profile
    process.scratch       = true
    process.maxRetries    = 3
    process.errorStrategy = 'terminate'
    process {
      withName: BUILD_FASTANI_PANEL { cpus = 4; time = '4h'; memory = '4 GB' }
      withName: FASTANI_BATCH       { cpus = 4; time = '2h'; memory = '4 GB' }
      withName: FASTANI_ANNOTATE_TYPES { cpus = 1; time = '30m'; memory = '1 GB' }
    }
  }
} 


